var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/[lang]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__ba5a5d6e._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_336638a4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d1f63313._.js")
R.c("server/chunks/ssr/[root-of-the-server]__867903a0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_a6fcb974._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_2dbefac6._.js")
R.c("server/chunks/ssr/_next-internal_server_app_[lang]_page_actions_6accbf08.js")
R.m(51526)
module.exports=R.m(51526).exports
