var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__cd6246d9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_de1b42a0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__037f67f8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__867903a0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_a6fcb974._.js")
R.c("server/chunks/ssr/node_modules_53db6af9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_554ec2bf.js")
R.m(16449)
module.exports=R.m(16449).exports
